version: '2'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://exports:exports@postgresql/exports
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_LOG_LEVEL=INFO
      - LOG_LEVEL=DEBUG
      - DJANGO_ENV=development
  celery-beat:
    extends:
      service: base
    depends_on:
      - base
      - postgresql
      - rabbitmq
    links:
      - postgresql
      - rabbitmq
    command: celery -A core beat
  celery:
    extends:
      service: base
    depends_on:
      - base
      - postgresql
      - rabbitmq
    links:
      - postgresql
      - rabbitmq
    environment:
      - CONCURRENCY=2
    command: celery -A core worker
  migration:
    extends:
      service: base
    depends_on:
      - postgresql
    links:
      - postgresql
    command: python manage.py migrate
  site:
    extends:
      service: base
    depends_on:
      - base
      - postgresql
      - rabbitmq
    expose:
      - "6080"
    links:
      - postgresql
      - rabbitmq
    ports:
      - "6080:6080"
    command: gunicorn core.wsgi:application --workers=3 --bind :6080
  # nginx:
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=exports
      - POSTGRES_PASSWORD=exports
      - POSTGRES_DB=exports
    expose:
      - "5432"
  rabbitmq:
    image: rabbitmq:3.6.8-management
    expose:
      - "5672"
