version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            set -x
            make test
